CREATE SEQUENCE SEQ_MEMBER;
CREATE TABLE TBL_MEMBER(
	ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
	MEMBER_EMAIL VARCHAR2(255) NOT NULL UNIQUE,
	MEMBER_PASSWORD VARCHAR2(255),
	MEMBER_ADDRESS VARCHAR2(255),
	MEMBER_RECOMMENDER_EMAIL VARCHAR2(255)
);


UPDATE TBL_MEMBER 
SET MEMBER_RECOMMENDER_EMAIL = 'hong1234@gmail.com'
WHERE ID = 2;

UPDATE TBL_MEMBER 
SET MEMBER_RECOMMENDER_EMAIL = 'hong1234@gmail.com'
WHERE ID = 3;

UPDATE TBL_MEMBER 
SET MEMBER_RECOMMENDER_EMAIL = 'kim7897@gmail.com'
WHERE ID = 1;

SELECT * FROM TBL_MEMBER;

SELECT ID, MEMBER_EMAIL, MEMNER_PASSWORD, MEMBER_ADDRESS, MEMBER_RECOMMENDER_EMAIL FROM TBL_MEMBER WHERE MEMBER_RECOMMENDER_EMAIL_= (
	SELECT MEMBER_EMAIL 
	FROM TBL_MEMBER ID = 1
);

