/*
 * GROUP BY부터 생각을 많이 해야한다.
 * FROM -> WHERE -> GROUP BY -> HAVING -> SELECT > ORDER BY
 * 
*/


SELECT * FROM TBL_REPLY;
SELECT * FROM TBL_POST;
SELECT * FROM TBL_USER;

SELECT TBP.*, TBU.USER_EMAIL  
FROM TBL_POST TBP
JOIN TBL_USER TBU 
ON TBP.USER_ID = TBU.ID;

SELECT TBR.REPLY_CONTENT, TBP.POST_TITLE  
FROM TBL_REPLY TBR 
JOIN TBL_POST TBP 
ON TBR.POST_ID = TBP.ID;


-- 댓글 테이블, 유저 테이블 조인 후
-- 댓글의 작성자와 댓글 내용을 조회
SELECT TBR.REPLY_CONTENT, TBU.USER_EMAIL 
FROM TBL_REPLY TBR
JOIN TBL_USER TBU 
ON TBR.USER_ID = TBU.ID;

-- 3개
-- 게시글 제목, 댓글 내용, 작성자
SELECT DISTINCT TBP.POST_TITLE
FROM TBL_REPLY TBR
JOIN TBL_USER TBU 
ON TBR.USER_ID = TBU.ID 
JOIN TBL_POST TBP 
ON TBR.POST_ID = TBP.ID
WHERE POST_TITLE LIKE '%유중의 미%';


-- 댓글이 2개 이상 달린 게시글의 작성자 이메일, 주소를 조회하기
SELECT DISTINCT TBU.USER_EMAIL, TBU.USER_ADDRESS 
FROM TBL_REPLY TBR
JOIN TBL_USER TBU 
ON TBR.USER_ID = TBU.ID 
JOIN TBL_POST TBP 
ON TBR.POST_ID = TBP.ID
WHERE TBP.ID IN (
	SELECT POST_ID 
	FROM TBL_REPLY
	GROUP BY POST_ID 
	HAVING COUNT(REPLY_CONTENT) >= 2 
);

--SELECT *
--FROM TBL_POST TBP
--JOIN (
--   SELECT POST_ID 
--   FROM TBL_REPLY
--   GROUP BY POST_ID
--   HAVING COUNT(POST_ID) >= 2
--) TBR
--ON TBP.ID = TBR.POST_ID;
--
--
--SELECT DISTINCT TBU.USER_EMAIL, TBU.USER_ADDRESS
--FROM (
--   SELECT POST_ID 
--   FROM TBL_REPLY
--   GROUP BY POST_ID
--   HAVING COUNT(POST_ID) >= 2
--) TBR
--JOIN TBL_POST TBP
--ON TBR.POST_ID = TBP.ID
--JOIN TBL_USER TBU 
--ON TBP.USER_ID = TBU.ID;


-- 내용에 뀨트북이 들어간 게시글의 달린 댓글 조회
SELECT * 
FROM TBL_REPLY
WHERE POST_ID IN (
	SELECT ID
	FROM TBL_POST
	WHERE POST_CONTENT LIKE '%뀨트북%'
);

-- 내용에 포도가 들어간 글을 작성한 작성자의 이메일 조회
SELECT USER_EMAIL 
FROM TBL_USER 
WHERE ID IN (
	SELECT USER_ID
	FROM TBL_POST
	WHERE POST_CONTENT LIKE '%포도%'
);

-- 2000년생 유저가 작성한 댓글 조회
SELECT REPLY_CONTENT 
FROM TBL_REPLY TBR
JOIN TBL_USER TBU 
ON TBR.USER_ID = TBU.ID 
WHERE TBU.USER_BIRTH >= '2000-01-01' AND TBU.USER_BIRTH <= '2000-12-31';

-- 가장 나이가 어린 사용자가 작성한 게시글 조회
SELECT POST_CONTENT 
FROM TBL_POST TBP
JOIN TBL_USER TBU 
ON TBP.USER_ID = TBU.ID 
WHERE TBU.USER_BIRTH = (
	SELECT MAX(USER_BIRTH)
	FROM TBL_USER 
); 

-- 주소가 '구'로 끝나는 유저가 작성한 게시글에 달린 모든 댓글 조회
SELECT TBR.REPLY_CONTENT 
FROM TBL_REPLY TBR
JOIN TBL_POST TBP 
ON TBR.POST_ID = TBP.ID 
JOIN TBL_USER TBU
ON TBP.USER_ID = TBU.ID 
WHERE TBU.USER_ADDRESS LIKE '%구';

-- 평균 댓글 개수보다 작게 달린 게시글을 작성한 유저 조회

-- 내용에 뀨트북이 들어간 게시글의 달린 댓글 조회
--SELECT * 
--FROM TBL_REPLY
--WHERE POST_ID IN (
--   SELECT ID
--   FROM TBL_POST
--   WHERE POST_CONTENT LIKE '%뀨트북%' OR POST_TITLE LIKE '%뀨트북%'
--);
--
-- 내용에 포도가 들어간 글을 작성한 작성자의 이메일 조회
--SELECT TBU.USER_EMAIL 
--FROM TBL_POST TBP
--JOIN TBL_USER TBU
--ON TBP.USER_ID = TBU.ID
--   AND TBP.POST_CONTENT LIKE '%포도%' 
--   OR TBP.POST_TITLE LIKE '%포도%';
--
-- 2000년생 유저가 작성한 댓글 조회
--SELECT TBR.*
--FROM TBL_REPLY TBR
--WHERE TBR.USER_ID IN (
--   SELECT TBU.ID
--   FROM TBL_USER TBU
--   WHERE TBU.USER_BIRTH >= TO_DATE('2000-01-01', 'YYYY-MM-DD') 
--      AND TBU.USER_BIRTH <= TO_DATE('2000-12-31', 'YYYY-MM-DD')
--);
--
-- 가장 나이가 어린 사용자가 작성한 게시글 조회
--SELECT TBP.*
--FROM TBL_POST TBP
--JOIN (
--   SELECT *
--   FROM TBL_USER
--   ORDER BY USER_BIRTH DESC
--   FETCH FIRST 1 ROWS ONLY
--) TBU
--ON TBP.USER_ID = TBU.ID;
--
--
--SELECT *
--FROM (
--   SELECT *
--   FROM TBL_USER
--   ORDER BY USER_BIRTH DESC
--)
--WHERE ROWNUM = 1;
--
-- 주소가 '구'로 끝나는 유저가 작성한 게시글에 달린 모든 댓글 조회
--
--SELECT TBP.USER_ID, TBR.*
--FROM (
--   SELECT TBU.*
--   FROM TBL_USER TBU
--   WHERE TBU.USER_ADDRESS LIKE '%구'
--) TBU
--JOIN TBL_POST TBP
--ON TBP.USER_ID = TBU.ID
--JOIN TBL_REPLY TBR
--ON TBR.POST_ID = TBP.ID;
--
--
-- 평균 댓글 개수보다 작게 달린 게시글을 작성한 유저 조회
-- 평균 개수;
--SELECT *
--FROM TBL_USER TBU
--JOIN (
--   SELECT TBP.USER_ID
--   FROM TBL_POST TBP
--   JOIN (
--      SELECT POST_ID
--      FROM TBL_REPLY
--      GROUP BY POST_ID
--      HAVING COUNT(POST_ID) < (
--         SELECT ROUND(AVG(POST_COUNT), 2)
--         FROM (
--            SELECT POST_ID, COUNT(POST_ID) AS POST_COUNT
--            FROM TBL_REPLY
--            GROUP BY POST_ID
--         )
--      )
--   ) TBR
--   ON TBR.POST_ID = TBP.ID
--) TBP 
--ON TBP.USER_ID = TBU.ID;

